### ISSUE TITLE
Create a Conan Package

### ISSUE THREAD

**Issue by hrantzsch** [hrantzsch/keychain#16]

**Comment by reneme** [comment]
WIP: https://github.com/reneme/conan-keychain

**Comment by reneme** [comment]
The [package](https://github.com/reneme/conan-keychain) works fine for Windows and macOS, but I'm stuck with the dependency resolution on Linux. `libsecret-1` is not packaged with `conan` and `pkg-config` refuses to pick up the system-installed version. At least on the build machine in GitHub actions. I have tried a few things on [this branch](https://github.com/reneme/conan-keychain/tree/stable/1.0) but didn't get far.

For now we (i.e. neXenio) will just skip the keychain integration on Linux and carry on. It would be cool to revisit this at some point, though. Maybe we could just try to upstream the recipe into bincrafters and get "professional" advice for this?

**Comment by christofmuc** [comment]
First, thank you for keychain! Great work! I am having problems using the conan package from conan center on a vanilla Ubuntu 20.04 desktop. The first weird thing is that on conan center, the profile I want is available as a binary release but it is not picked up. Not sure how to debug this. My profile is 

conan profile show default
Configuration for profile default:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

So I would think this package should be picked up, but it isn't (at https://conan.io/center/keychain?os=Linux&tab=configuration): _/keychain/1.2.0/_/a97a0e3009474f5e46a975db0bab41cc/c5ad7cd4f10f99b43121e8d15bbe26183c7bceed/d1c613317981258e8e6cc2320a5216b5

I am really not sure how conan center works and how these IDs belong to each other.

What is worse, building it afresh also fails during a conan install step. With a minimal conanfile.py

```
from conans import ConanFile
from os import path

class JammerNetzConan(ConanFile):
    requires = ["keychain/1.2.0"]
    generators = "cmake", "cmake_find_package", "json", "virtualenv"

```
and running 

    conan install . --build missing

I get the error 

    keychain/1.2.0: ERROR: Generator pkg_config(file:None) failed
    Component 'libgcrypt::gcrypt' not found in 'libgcrypt' package requirement
    ERROR: Component 'libgcrypt::gcrypt' not found in 'libgcrypt' package requirement

If I cd into the build directory inside the .conan hierarchy's directory, I can build it using cmake -S . -B build && cmake --build build, so all prerequisites are installed.

Any idea how to debug this? Cheers!

**Comment by hrantzsch** [comment]
Hi Christof,
that is strange. I get the same libgcrypt error when I try to build a minimal package. I'll try to look into it tomorrow. Meanwhile, can you post the output of `conan --version` and `conan remote list`?

**Comment by christofmuc** [comment]
conan --version
    Conan version 1.42.2

    conan remote list
    conancenter: https://center.conan.io [Verify SSL: True]

Thanks for getting back to me quickly! I'll leave it though for the holidays and will be back on this project only Jan 3rd. I am moving our stuff now to conan at full scale, as it really helps us dealing with all the dependencies and the build times, especially given that I normally build RelWithDebInfo or other arcane versions that are not available in binary form anyway - this is why I hadn't even thought checking if there is a binary package available in the first place, normally I build on the CI system and push to an artifactory.

This somehow looks like a regression, I just can't spot at which point in the chain it breaks. To confirm - it builds fine on Windows and Mac, so maybe some sub-recipe of libgcrypt is freaking out.

**Comment by hrantzsch** [comment]
Just a quick update, I haven't been able to figure out what the issue is yet. I hope someone from the conan team [can help](https://github.com/conan-io/conan-center-index/issues/8601) and I'll continue to investigate next week.

**Comment by hrantzsch** [comment]
The libsecret recipe [has been fixed](https://github.com/conan-io/conan-center-index/pull/8602) :tada: 
I can no longer reproduce the issue. Does it work for you as well?

**Comment by christofmuc** [comment]
@hrantzsch Thank you, I can confirm it works again! I can build a RelWithDebInfo as well as retrieve a matching Debug as binary from conan center. Happy new year and thanks again!
