### ISSUE TITLE
Build/installation/usage

### ISSUE THREAD

**Issue by dawinaj** [hrantzsch/keychain#27]
Hello,
could you _PLEASE_ make a better tutorial on that... I'm not really familiar with neither linux nor cmake nor git nor anything.

When cloning from master, I get
```
test cases:  1 |  1 failed
assertions: 12 | 12 failed
```

[pastebin](https://pastebin.com/wChpWLDa)

When I downloaded the last release (v1.2.0), I had a different error, and it didn't even build
```
[ 20%] Building CXX object test/CMakeFiles/catchmain.dir/main.cpp.o
In file included from /usr/include/signal.h:328,
                 from /media/keychain/test/catch.hpp:7937,
                 from /media/keychain/test/main.cpp:7:
/media/keychain/test/catch.hpp:10717:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10717 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /media/keychain/test/catch.hpp:7937,
                 from /media/keychain/test/main.cpp:7:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /media/keychain/test/main.cpp:7:
/media/keychain/test/catch.hpp:10776:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10776 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
gmake[3]: *** [test/CMakeFiles/catchmain.dir/build.make:76: test/CMakeFiles/catchmain.dir/main.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:129: test/CMakeFiles/catchmain.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:189: test/CMakeFiles/test.dir/rule] Error 2
gmake: *** [Makefile:208: test] Error 2
-- Install configuration: ""
CMake Error at _build/cmake_install.cmake:46 (file):
  file INSTALL cannot find "/media/keychain/_build/libkeychain.a": No such
  file or directory.
```

However, I tried it with the files created by 1st method, but it didn't work. I added `keychain` to the linker and no luck.
![image](https://user-images.githubusercontent.com/7432818/187297651-6b832d7f-9286-4353-9b27-9f5d389699ce.png)

**Comment by hrantzsch** [comment]
Hi, what is your OS and compiler version? Just to be sure, have you installed libsecret using apt / your package manager, [as described here](https://github.com/hrantzsch/keychain#building-it-manually)?

**Comment by dawinaj** [comment]
Yes, I had libsecret installed already, so it did not pull a new one.
I am building on Ubuntu Server with gcc
`Linux [...] 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` and `gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0`
through a Visual Studio remote develompent (SSH) on Win10.
`Microsoft Visual Studio Community 2022 (64-bit) - Current | Version 17.3.2`
I also tried linking libsecret and glib-2.0 in the VS but it didn't do anything.

Sorry if I were a bit rude in the original message, I was kinda fed up ;)

**Comment by hrantzsch** [comment]
OK, the build error on 1.2.0 results from the outdated Catch version being incompatible with gcc. I have updated Catch on master.
I will make a new release with the update soon. For now you can get around it by not building the tests:

```sh
mkdir _build
cmake . -DBUILD_TESTS=no -B _build
cmake --build _build
```

Note that this will not get rid of your other issue.

The other issue you encounter on master happens because you're not running in a full desktop session but through an SSH connection. You need to "kickstart" gnome-keyring-daemon. [The same is necessary in our CI build](https://github.com/hrantzsch/keychain/blob/44b517d0962c83cce31c190a6be44c3ddbf52d50/.github/workflows/ci.yml#L49-L54). Try this:

```sh
export DISPLAY=:99.0
eval $(dbus-launch --sh-syntax)
echo '$(whoami)' | gnome-keyring-daemon -r -d --unlock
cmake . -DBUILD_TESTS=yes -B _build
cmake --build _build --target test
```

Let me know if that works for you :)

**Comment by dawinaj** [comment]
Well, so I tried following:
Installed `gnome-keyring` xD
Installed `dbus-x11` (for `dbus-launch`)

The `echo '$(whoami)'` doesn't work, returns plain string. Consider replacing with `whoami` or `echo $(whoami)` or `echo "$(whoami)"` or `echo $USER` ;)
I also changed the order of linking in my VS, because for some inconceivable reason

> In general, if library A depends on library B which inturn depends on library C, the linker order should be -lA -lB -lC

So I put `keychain;secret-1;glib-2.0` and it finally compiled.
Now gotta see if it actually works.

Ed1: Now I get `Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached` while running the program, on `setPassword()`

Ed2: Alright that fixed after a restart, but now I get `Cannot create an item in a locked collection`
Ed3: That happens when running as root, when running as an user i get `Object does not exist at path “/org/freedesktop/secrets/collection/login”`
Ed4: I got it to work after adding `export $(printf "%s" "password" | gnome-keyring-daemon --replace --daemonize --unlock)` to a bashrc, but it only works for one user (and each user has a separate keyring obviously which is kilda undesirable when I want an app to have access to it) + feels a lot whacky, so I might give up on the idea anyway.

**Comment by hrantzsch** [comment]
> Installed gnome-keyring xD

Fair enough. I'll add that to the readme just in case.

> `echo '$(whoami)'` doesn't work, returns plain string.

Good catch. Turns out it doesn't matter what we put in there, it just creates and unlocks the keyring initially. I'll simplify this to make it less confusing.

> feels a lot whacky, so I might give up on the idea anyway

Might I ask what you're building?

**Comment by dawinaj** [comment]
To put it simply, I am writing a daemon. It needs to have access to local DB, external DB, external API, etc. So a lot of secrets/credentials I'd rather not keep inside the code. I thought about using keyring but failed to realize that it is per-user based.
Will probably go with a simple Keepass file and some cpp parser.
Thanks for the help, I'm glad I could contribute at least a tiny bit too :P

**Comment by hrantzsch** [comment]
I've never used keepass tbh, but I imagine you might encounter a similar problem with a keepass file.

Keychain's "backends" on all OSs use the user login as an external secret. Without anything like that, what do you encrypt the API secrets with? Keypass will need a master key, and if you store the master key on disk next to the API secrets you don't gain that much.

That said, storing API secrets in plaintext (or quasi plaintext) on the harddrive is a common and valid approach in many scenarios, and certainly better than having the secrets in the codebase :)
