### ISSUE TITLE
Add to vcpkg.io package manager

### ISSUE THREAD

**Issue by Jaegermeiste** [hrantzsch/keychain#29]
Add package 'keychain' to the Visual C++ package repo.

See https://vcpkg.io/en/docs/maintainers/maintainer-guide.html for implementation details, but this basically enables simple deployment of keychain to a project via `vcpkg install keychain`.

In practice, this involves creating 3 files and modifying one in the [vcpkg](https://github.com/microsoft/vcpkg) repo, including making a vcpkg.json, something like this:
```
{
  "name": "keychain",
  "version-semver": "1.2.0",
  "description": "A thin cross-platform wrapper to access the operating system's credential storage in C++",
  "homepage": "https://github.com/hrantzsch/keychain",
  "license": "MIT",
  "dependencies": [
    {
      "name": "libsecret",
      "platform": "(linux & x32) | (linux & x64)"
    }
  ]
}
```
a portfile.cmake file, something along these lines (I'm not good with cmake, so this example likely doesn't work right):
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO hrantzsch/keychain
    REF 6a4db6048559516fb2f30ad449152a0a3c7138a0 #v1.2.0
    SHA512 6422d3d5b59a700ac56730870dab1bbdadd8f85c9a0cef2c685cdd36189b1689d04d5a710500fbc5299445ca32df9434b404fae3018e8266c284aa34259f110a
    HEAD_REF master
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        ${OPTIONS}
)

vcpkg_cmake_install(ADD_BIN_TO_PATH)

if(VCPKG_TARGET_IS_LINUX)
    if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
        if(EXISTS "${CURRENT_PACKAGES_DIR}/lib/libsecret.so")
            file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/bin")
            file(RENAME "${CURRENT_PACKAGES_DIR}/lib/libsecret.so" "${CURRENT_PACKAGES_DIR}/bin/libsecret.so")
        endif()
        if(EXISTS "${CURRENT_PACKAGES_DIR}/debug/lib/libsecretd.so")
            file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/debug/bin")
            file(RENAME "${CURRENT_PACKAGES_DIR}/debug/lib/libsecretd.so" "${CURRENT_PACKAGES_DIR}/debug/bin/libsecretd.so")
        endif()
    endif()
endif()

vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/${PORT})

vcpkg_fixup_pkgconfig()

vcpkg_copy_pdbs()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

a versions/k-/keychain.json:
```
{
  "versions": [
    {
      "git-tree": "6a4db6048559516fb2f30ad449152a0a3c7138a0",
      "version": "1.2.0",
      "port-version": 0
    }
  ]
}
```
and modifying versions/baseline.json to include keychain:
```
...
    "keychain": {
      "baseline": "1.2.0",
      "port-version": 0
    },
...
```

For those unfamiliar, vcpkg is the standard cross-platform (win32, win64, winarm, ios, macos, linux, android) package repository for the Visual Studio/MSBuild/CMake (and VSCode with a little bit of work) ecosystem (akin to NuGet, but for C/C++).

**Comment by hrantzsch** [comment]
Thanks for the suggestion and the pointers and scaffolds! I'll look into it. (Probably not before next week though)

**Comment by hrantzsch** [comment]
It took a bit longer than I had hoped, but I have now created a port for keychain (largely on the drafts you provided). `vcpkg install keychain` seems to run without issues.

However, I haven't created a PR to vcpkg yet because I struggle to use the package. Is keychain expected to provide a keychainConfig.cmake file (in the upstream repo or as part of the port)? I was hoping the cmake toolchain file that comes with vcpkg takes care of this, but that doesn't seem to be the case.

Could you maybe try it out or sketch out how the port would be consumed in a project?

You can find the port here on branch keychain: https://github.com/hrantzsch/vcpkg/tree/keychain

**Comment by hrantzsch** [comment]
Closing this -- honestly I don't think that I will pick this back up. Contributions are welcome of course and maybe the port linked above (this is the relevant commit: https://github.com/microsoft/vcpkg/commit/7f867707548b9ddde225d54f5b42e083f40a4b63) can help to get started.

**Comment by reneme** [comment]
>  Is keychain expected to provide a keychainConfig.cmake file (in the upstream repo or as part of the port)?

Typically, you would provide such a file as part of your library installation. If provided, the keychainConfig.cmake is used by CMake to find your package in downstream projects. See: [CMakePackageConfigHelpers](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html).
