### ISSUE TITLE
New conan release to include MacOS fix

### ISSUE THREAD

**Issue by fklebert** [hrantzsch/keychain#32]
We have been using keychain for a while as a submodule. We are now trying to use it via `conan` and figured out that the latest version on conan-center is 1.2.0 which does not have the MacOS deprecated warning fix in.
Is there any chance to get a new release on conan-center that includes this?

**Comment by hrantzsch** [comment]
Oh, sure! I wasn't sure if the fix warranted a new release, but if the conan package is broken I'll make a release and update the package on conan-center.

**Comment by hrantzsch** [comment]
Hey, I'm sorry, this is taking so much longer than I had hoped. Maybe you saw that I tagged the release already a while ago. However, to get the Conan recipe published in the CCI I need to make it compatible with Conan 2, which I currently don't have the time to look into in depth.

If you're not using Conan 2 yet, you should be fine if you just add the new version and its hash. With Conan 1.60 it should work.

**Comment by fklebert** [comment]
Awesome! Thanks. We also have not yet switched to Conan 2 as it did not work seamlessly so far.

**Comment by hrantzsch** [comment]
I'm happy to report that, thanks to the support of the conan center team, version 1.2.1 is finally available for both conan 1.60 and conan 2.0 from the conan center.
